name: Build and Push

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Get current timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Build
      uses: docker/setup-buildx-action@v3
    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: learningfeeds.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          learningfeeds.azurecr.io/learning-feeds/server:latest
          learningfeeds.azurecr.io/learning-feeds/server:${{ steps.timestamp.outputs.timestamp }}
        secrets: |
          "LINKEDIN_CLIENT_ID=${{ secrets.LINKEDIN_CLIENT_ID }}"
          "LINKEDIN_CLIENT_SECRET=${{ secrets.LINKEDIN_CLIENT_SECRET }}"
