name: Trigger auto deployment for learning-feeds

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/learning-feeds-AutoDeployTrigger-d4fb9916-cb2a-44a9-ad10-cff1abc4b2f1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.LEARNINGFEEDS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LEARNINGFEEDS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LEARNINGFEEDS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: learningfeeds.azurecr.io
          registryUsername: ${{ secrets.LEARNINGFEEDS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LEARNINGFEEDS_REGISTRY_PASSWORD }}
          containerAppName: learning-feeds
          resourceGroup: learning-feeds
          imageToBuild: learningfeeds.azurecr.io/learning-feeds:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


